version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - '3001:3000'

volumes:
  mysql_data:
